name: name: Wheel::Linux::x86_64

on:
  pull_request:
  push:
    branches:
      - master
  release:
    types: [published]

concurrency:
  group: wheel_linux_x86_64-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build_wheels:
    name: Build wheels on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        arch: [x86_64]
        container_img: ["quay.io/pypa/manylinux2014_x86_64"]
      container: ${{ matrix.container_img }}

    steps:
      - uses: actions/checkout@v4
        
      - name: Install cibuildwheel
        run: python3.9 -m pip install cibuildwheel~=2.11.0

      - name: Build wheels
        env:
          CIBW_BEFORE_BUILD: |
            cat /etc/yum.conf | sed "s/\[main\]/\[main\]\ntimeout=5/g" > /etc/yum.conf
            python -m pip install cmake~=3.24.0
            yum clean all -y
            yum install devtoolset-11-gcc-c++ -y
            yum install mpfr
            yum install boost boost-thread boost-devel

          CIBW_MANYLINUX_X86_64_IMAGE: manylinux2014

        run: python3.9 -m cibuildwheel --output-dir wheelhouse

      - uses: actions/upload-artifact@v3
        with:
          path: ./wheelhouse/*.whl
